# Generated by Django 3.1.2 on 2020-11-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='audio_file',
            new_name='song',
        ),
    ]
